name: refrescate
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_pin_code_fields: ^1.1.0
  flutter_spinkit: 4.1.2+1
  table_calendar: ^2.3.3
  sqflite: ^1.3.0
  path_provider: 1.6.27
  flutter_bloc: 6.1.1
  cupertino_icons: ^0.1.3
  http: 0.12.2
  flutter_webview_plugin: 0.3.11
  flutter_secure_storage: 3.3.5
  firebase_core: 0.5.3
  firebase_auth: 0.18.4

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/appstore.png"
  image_path_android: "assets/launcher/playstore.png"
flutter:
  uses-material-design: true
  assets:
    - assets/
